### ISSUE TITLE
Support net.tsinghua.edu.cn

### ISSUE THREAD

**Issue by ritou11** [z4yx/GoAuthing#2]
Currently we are still using it for "Tsinghua" & "Tsinghua-5G".

**Comment by z4yx** [comment]
https://github.com/syimyuzya/tunet-cli is dedicated for that purpose and works fine.

**Comment by ritou11** [comment]
> https://github.com/syimyuzya/tunet-cli is dedicated for that purpose and works fine.

Yep. In fact, I have a repo https://github.com/ritou11/thunet-reg based on Node.js. It could satisfy my daily routine.
However, "thunet-reg" is written in JS, and "tunet-cli" is written in Python. Both of them require extra environments currently such as Node or Python. Since Golang is easy to compile and release, I'm taking it as the best language in this situation.

**Comment by z4yx** [comment]
If JS and Python are too heavy, why not use `curl` to do this job.

`curl -sL net.tsinghua.edu.cn/do_login.php --data "action=login&username=yourID&password={MD5_HEX}yourPasswdMD5&ac_id=1"`

Since  *net.tsinghua* will soon be replaced by *auth*, I'm not motivated to add this feature. But PR is always welcomed.

**Comment by ritou11** [comment]
I did use `curl` for this years ago by writing a bash script. Similar to #3 , it's kind of a fancy function but counts in my personal daily use indeed.
